### ISSUE TITLE
因为找不到你的邮件就直接在这里给你了

### ISSUE THREAD

**Issue by LSP0123** [liamwu-workspace/python#1]
steamtool的issue已经关闭，我就不再打开议题了，对wiki有需求可以看下这个，基本够用。https://github.com/mashirozx/Pixiv-Nginx

**Comment by liamwu-workspace** [comment]
多谢分享🙏🏻🙏🏻



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月24日 11:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [liamwu-workspace/python] 因为找不到你的邮件就直接在这里给你了 (Issue #1) |

steamtool的issue已经关闭，我就不再打开议题了，对wiki有需求可以看下这个，基本够用。https://github.com/mashirozx/Pixiv-Nginx
